repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: no-commit-to-branch
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: detect-private-key
  - id: check-merge-conflict
  - id: check-json
  - id: check-yaml
    args: ['--unsafe']
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
  - id: isort
    args: ["--profile", "black"]
- repo: https://github.com/ambv/black
  rev: 21.7b0
  hooks:
  - id: black
    entry: bash -c 'python -m black "$@"; git add -u' --
    language_version: python3.6
- repo: https://github.com/pycqa/flake8
  rev: 3.9.2
  hooks:
  - id: flake8
    entry: bash -c 'flake8 "$@"; git add -u' --
